/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hello
 */
public class LoginView extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form Coffee
	 */
	public LoginView() {
		initComponents();
		setLocationRelativeTo(null);
		setResizable(false);
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		pnlWrapper = new javax.swing.JPanel();
		pnlLogin = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		txtUsername = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		txtPassword = new javax.swing.JPasswordField();
		btnExit = new javax.swing.JButton();
		btnLogin = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Đăng nhập");
		setMinimumSize(new java.awt.Dimension(400, 200));
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});
		ImageIcon logo = new ImageIcon(getClass().getResource("/images/logo.png"));
		setIconImage(logo.getImage());
		pnlLogin.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel3.setText("Tên đăng nhập:");
		pnlLogin.add(jLabel3);
		pnlLogin.add(txtUsername);

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel2.setText("Mật khẩu:");
		pnlLogin.add(jLabel2);
		pnlLogin.add(txtPassword);

		btnExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
		btnExit.setText("Thoát");
		btnExit.setFocusPainted(false);
		btnExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExitActionPerformed(evt);
			}
		});

		btnLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
		btnLogin.setFocusPainted(false);
		btnLogin.setText("Đăng nhập");
		javax.swing.GroupLayout pnlWrapperLayout = new javax.swing.GroupLayout(pnlWrapper);
		pnlWrapper.setLayout(pnlWrapperLayout);
		pnlWrapperLayout.setHorizontalGroup(pnlWrapperLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlWrapperLayout.createSequentialGroup()
						.addGroup(pnlWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlWrapperLayout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnLogin).addGap(18, 18, 18).addComponent(btnExit,
												javax.swing.GroupLayout.PREFERRED_SIZE, 121,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(pnlWrapperLayout.createSequentialGroup().addGap(5, 5, 5).addComponent(
										pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)))
						.addContainerGap()));
		pnlWrapperLayout.setVerticalGroup(pnlWrapperLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlWrapperLayout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 69,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(26, 26, 26)
						.addGroup(pnlWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(pnlWrapper,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(pnlWrapper,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExitActionPerformed
		exitApplication();
	}

	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		exitApplication();
	}

	private void exitApplication() {
		int choice = JOptionPane.showConfirmDialog(this, "Bạn có thật sự thoát chương trình?", "Exit",
				JOptionPane.OK_CANCEL_OPTION);
		if (choice == 0) {
			System.exit(0);
		} else {
			setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnExit;
	private javax.swing.JButton btnLogin;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel pnlLogin;
	private javax.swing.JPanel pnlWrapper;
	private javax.swing.JPasswordField txtPassword;
	private javax.swing.JTextField txtUsername;

	// End of variables declaration//GEN-END:variables
	public javax.swing.JButton getBtnLogin() {
		return btnLogin;
	}

	public javax.swing.JPasswordField getTxtPassword() {
		return txtPassword;
	}

	public javax.swing.JTextField getTxtUsername() {
		return txtUsername;
	}

	public void clear() {
//		txtUsername.setText("");
		txtPassword.setText("");
	}
}
